name: phpMyBlog
services:
  webserver:
    container_name: webserver
    build: .
    ports:
      - "80:80"
      - "8025:8025"
    volumes:
      - ./:/sites/localhost/html/public/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  adminpanel:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  db_data:
